### ISSUE TITLE
Fatal error - concurrent map read and write

### ISSUE THREAD

**Issue by muety** [muety/caddy-pirsch-plugin#1]
There currently is a critical error that gets Caddy to crash with the following error:

```
Oct 05 01:11:04 localhost caddy[31157]: fatal error: concurrent map read and map write
Oct 05 01:11:04 localhost caddy[31157]: goroutine 9422 [running]:
Oct 05 01:11:04 localhost caddy[31157]: runtime.throw(0x19679fa, 0x21)
Oct 05 01:11:04 localhost caddy[31157]:         runtime/panic.go:1117 +0x72 fp=0xc0004e0538 sp=0xc0004e0508 pc=0x438592
Oct 05 01:11:04 localhost caddy[31157]: runtime.mapaccess1_faststr(0x17db0a0, 0xc000384f00, 0xc000566ad8, 0x3, 0x25f9300)
Oct 05 01:11:04 localhost caddy[31157]:         runtime/map_faststr.go:21 +0x465 fp=0xc0004e05a8 sp=0xc0004e0538 pc=0x414045
Oct 05 01:11:04 localhost caddy[31157]: net/textproto.MIMEHeader.Get(0xc000384f00, 0x18f022c, 0x3, 0xc000896048, 0x20)
Oct 05 01:11:04 localhost caddy[31157]:         net/textproto/header.go:34 +0x5f fp=0xc0004e05e0 sp=0xc0004e05a8 pc=0x689a5f
Oct 05 01:11:04 localhost caddy[31157]: net/http.Header.Get(...)
Oct 05 01:11:04 localhost caddy[31157]:         net/http/header.go:46
Oct 05 01:11:04 localhost caddy[31157]: github.com/pirsch-analytics/pirsch-go-sdk.(*Client).HitWithOptions(0xc0000ef8c0, 0xc000ab0900, 0x0, 0xc000ab0600, 0xc000030000)
Oct 05 01:11:04 localhost caddy[31157]:         github.com/pirsch-analytics/pirsch-go-sdk@v1.4.0/client.go:115 +0x59 fp=0xc0004e06c8 sp=0xc0004e05e0 pc=0x1591299
Oct 05 01:11:04 localhost caddy[31157]: github.com/pirsch-analytics/pirsch-go-sdk.(*Client).Hit(...)
Oct 05 01:11:04 localhost caddy[31157]:         github.com/pirsch-analytics/pirsch-go-sdk@v1.4.0/client.go:110
Oct 05 01:11:04 localhost caddy[31157]: github.com/muety/caddy-pirsch-plugin.(*PirschPlugin).ServeHTTP.func1(0xc000ed29b0, 0xc000ab0900)
Oct 05 01:11:04 localhost caddy[31157]:         github.com/muety/caddy-pirsch-plugin@v0.0.0-20211003144434-4e076b518c4b/plugin.go:46 +0x5a fp=0xc0004e07d0 sp=0xc0004e06c8 pc=0x1599eda
Oct 05 01:11:04 localhost caddy[31157]: runtime.goexit()
Oct 05 01:11:04 localhost caddy[31157]:         runtime/asm_amd64.s:1371 +0x1 fp=0xc0004e07d8 sp=0xc0004e07d0 pc=0x472681
Oct 05 01:11:04 localhost caddy[31157]: created by github.com/muety/caddy-pirsch-plugin.(*PirschPlugin).ServeHTTP
Oct 05 01:11:04 localhost caddy[31157]:         github.com/muety/caddy-pirsch-plugin@v0.0.0-20211003144434-4e076b518c4b/plugin.go:45 +0x4d
Oct 05 01:11:04 localhost caddy[31157]: goroutine 1 [select (no cases), 47 minutes]:
Oct 05 01:11:04 localhost caddy[31157]: github.com/caddyserver/caddy/v2/cmd.cmdRun(0xc0000783c0, 0x0, 0x0, 0x0)
Oct 05 01:11:04 localhost caddy[31157]:         github.com/caddyserver/caddy/v2@v2.4.5/cmd/commandfuncs.go:275 +0x1395
Oct 05 01:11:04 localhost caddy[31157]: github.com/caddyserver/caddy/v2/cmd.Main()
Oct 05 01:11:04 localhost caddy[31157]:         github.com/caddyserver/caddy/v2@v2.4.5/cmd/main.go:85 +0x25b
Oct 05 01:11:04 localhost caddy[31157]: main.main()
Oct 05 01:11:04 localhost caddy[31157]:         caddy/main.go:14 +0x25
```

Looks like a race condition, I'll fix this as soon as possible.

**Comment by muety** [comment]
Fixed with https://github.com/muety/caddy-pirsch-plugin/commit/6319266447ab38864db696b7391e9efb52225558
